### ISSUE TITLE
Infos wanted

### ISSUE THREAD

**Issue by rhaamo** [Floppie209/Amiga2000-remake#1]
hi, contacting you here since I can't find anything else.

Have you taken notes of components values when removing then ?
The only available schematics is https://www.amigawiki.org/dnl/schematics/A2000_R6.pdf and seems to be a 6.0 one and some values are missing (which seems to change between revisions : http://eab.abime.net/showthread.php?t=77864)

If you have made scans before sanding this would be a wonderful thing to easily see where the labels are too !

Any reasons of doing it this way of only a PCB (with a paid software) instead of doing a schematics, then a new PCB layout ? (except doing more work)

**Comment by Floppie209** [comment]
Sorry for the answer delay,

To answer your questions. I did take a pictures before sanding the pcb so I know where all the components go and also I made lists of a the components and put the components on the list with tape.
I also noted all the values down and made detailed pictures of the pcb with all the components still in place.

The reason why I do it this way is that I want an exact copy of the board and it is easier to trace the original pcb than to first draw the complete schematic and make a board of that. And the cost for the software is ony 49 euro's. Thats a price I am willing tot pay for software. Eagle will cost me a minimal of 18 euro's a month.

I hope I answered all your questions I just updated the sprint layout file and have begun with the solderside.

**Comment by rhaamo** [comment]
hey, thanks !

Yeah for 1:1 replica that seems to be the best way anyway, as I've seen others doing the same with that software.

I'm doing schematics and pcb from scratch personally from a 6.0 schematics scans and my board for some things.

Would you like to share the other pictures and infos you have already done ?
I've found that the internet doesn't seems to have a lot of good (quality) pictures of that amiga, I'm using my rev 6.2 board actually and that's a bit big and uneasy to move around without getting anything damaged.

**Comment by Floppie209** [comment]
Yes of course, no problem.

I wil make zip files tomorow and put them on the github page.
Thanks for the reply.

Greetz

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: Marc Lagrange <notifications@github.com>
Verzonden: Thursday, May 30, 2019 8:51:41 PM
Aan: Floppie209/Amiga2000-remake
CC: Floppie209; Comment
Onderwerp: Re: [Floppie209/Amiga2000-remake] Infos wanted (#1)


hey, thanks !

Yeah for 1:1 replica that seems to be the best way anyway, as I've seen others doing the same with that software.

I'm doing schematics and pcb from scratch personally from a 6.0 schematics scans and my board for some things.

Would you like to share the other pictures and infos you have already done ?
I've found that the internet doesn't seems to have a lot of good (quality) pictures of that amiga, I'm using my rev 6.2 board actually and that's a bit big and uneasy to move around without getting anything damaged.

**Comment by Floppie209** [comment]
Marc,

I tried to put the pictures on Github but almost 800 MB is to big even in small parts.
Do you use usenet? As I can post them on usenet if you want. (Thats the easiest way for me)
Or maybe we can try FTP.
If you have another solution I would certenly like to know.

Greetz

Jeroen
Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: Marc Lagrange <notifications@github.com>
Verzonden: Thursday, May 30, 2019 8:51:41 PM
Aan: Floppie209/Amiga2000-remake
CC: Floppie209; Comment
Onderwerp: Re: [Floppie209/Amiga2000-remake] Infos wanted (#1)


hey, thanks !

Yeah for 1:1 replica that seems to be the best way anyway, as I've seen others doing the same with that software.

I'm doing schematics and pcb from scratch personally from a 6.0 schematics scans and my board for some things.

Would you like to share the other pictures and infos you have already done ?
I've found that the internet doesn't seems to have a lot of good (quality) pictures of that amiga, I'm using my rev 6.2 board actually and that's a bit big and uneasy to move around without getting anything damaged.

**Comment by rhaamo** [comment]
Yes I can share you an upload link, can you send me an email (on my profile) ?

**Comment by Floppie209** [comment]
Is the dashie@sigpipe.me<mailto:dashie@sigpipe.me> the emailadres of your profile?

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: Marc Lagrange <notifications@github.com>
Verzonden: Friday, May 31, 2019 10:04:45 AM
Aan: Floppie209/Amiga2000-remake
CC: Floppie209; Comment
Onderwerp: Re: [Floppie209/Amiga2000-remake] Infos wanted (#1)


Yes I can share you an upload link, can you send me an email (on my profile) ?

**Comment by rhaamo** [comment]
yes

**Comment by Floppie209** [comment]
They are on the way.
I hope they can help you.

By the way there is a german guy named gonzo who has already made the schematics and a pcb of the amiga2000 rev 6.2 in Eagle.
He promised me the files but until now he send me nothing.

Greetz

Jeroen

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: Marc Lagrange <notifications@github.com>
Verzonden: Friday, May 31, 2019 12:19:44 PM
Aan: Floppie209/Amiga2000-remake
CC: Floppie209; Comment
Onderwerp: Re: [Floppie209/Amiga2000-remake] Infos wanted (#1)


yes

**Comment by rhaamo** [comment]
Thanks !

Are the PCB faults issues when desoldering or it might be factory done ? (I can compare with my 6.2 one)

Might be one from the a1k forum, but no publicly available stuff..

I'm doing it with KiCAD here, eagle is 100E/month for a PCB this size unfortunately.

**Comment by Floppie209** [comment]
The faults are from desoldering. Its an old board and sometimes a little piece lets go.
And yes he is from the a1k forum. He promised to mail me the eagle files but until now nothing. He told me not to redistribute them because of license issues.
When youre done with Kicad I can check your files as well as two people see more than one. Yust let me know. You have my email.

Hope you can use the photo’s

Greetz


Jeroen

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: Marc Lagrange <notifications@github.com>
Verzonden: Friday, May 31, 2019 1:18:02 PM
Aan: Floppie209/Amiga2000-remake
CC: Floppie209; Comment
Onderwerp: Re: [Floppie209/Amiga2000-remake] Infos wanted (#1)


Thanks !

Are the PCB faults issues when desoldering or it might be factory done ? (I can compare with my 6.2 one)

Might be one from the a1k forum, but no publicly available stuff..

I'm doing it with KiCAD here, eagle is 100E/month for a PCB this size unfortunately.
