### ISSUE TITLE
448	R401	1k			Top	- Where is it???

### ISSUE THREAD

**Issue by KaosLord** [Floppie209/Amiga2000-remake#8]
The locator seem to have skipped this one and I'm presently going blind and a bit crazy trying to find it... Can somebody give me a clue where it is?

**Comment by rhaamo** [comment]
Where is this R401 located ? And which board revision ?

I can't locate it in either schematics, my own repro schematics or one available BOM.

**Comment by KaosLord** [comment]
Amiga2000rev6.2.incl.mods.1.8.5.BOM.txt

448	R401	1k			Top

Line 452 in the text file. I'm building the pcb I got  from: https://www.tindie.com/products/bobsbits/amiga-2000-replica-pcb-by-floppie209/

I'm unable to locate that part and it's absent from the locator.

**Comment by rhaamo** [comment]
Probably a typo leftover from an older revision, that resistor isn't mentionned in the xlsx sheet, nor https://docs.google.com/spreadsheets/d/15iEQ0hM72iEbbcy1ZybIc3_K2UyTCFhJ_Zc4mvceAfE/edit

**Comment by KaosLord** [comment]
Thanks!
